#!/usr/bin/env bash
#
# export.sh — capture the current Rectangle settings into the repo.
#
# Run this after changing a Rectangle shortcut/setting to update the tracked
# config. It exports the live macOS prefs, strips machine-specific and
# update-tracker noise, and normalizes to readable XML for clean git diffs.
# Re-apply on another machine via bootstrap.sh (`defaults import`).

set -euo pipefail

DOMAIN="com.knollsoft.Rectangle"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/RectangleConfig.plist"

# Keys that are machine-specific or regenerated by the app — not worth tracking.
NOISE_KEYS=(
  "NSWindow Frame SUUpdateAlert"
  "NSWindow Frame SUUpdateAlert2"
  "SUEnableAutomaticChecks"
  "SUHasLaunchedBefore"
  "SULastCheckTime"
  "SUUpdateGroupIdentifier"
  "installVersion"
  "lastVersion"
  "internalTilingNotified"
)

printf '\033[1;34m==>\033[0m Exporting %s...\n' "$DOMAIN"
defaults export "$DOMAIN" "$OUT"

for key in "${NOISE_KEYS[@]}"; do
  plutil -remove "$key" "$OUT" >/dev/null 2>&1 || true
done

plutil -convert xml1 "$OUT"
plutil -lint "$OUT"
printf '\033[1;32m  ✓\033[0m Wrote %s\n' "$OUT"
